name: ai-ci-cd

on:
  push:
    branches: ["develop"]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/t-curity/ai

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune -a -f
          df -h

      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:sha-${{ github.sha }}
            ${{ env.IMAGE }}:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger infra-deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          repository: t-curity/infra-deploy
          event-type: deploy-ai
          client-payload: |
            {"service":"ai","tag":"sha-${{ github.sha }}"}