name: backend-ci-cd

on:
  push:
    branches: ["develop"]

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/t-curity/backend

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:sha-${{ github.sha }}
            ${{ env.IMAGE }}:develop

      - name: Trigger infra-deploy (general/backend)
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          repository: t-curity/infra-deploy
          event-type: deploy-backend
          client-payload: |
            {"service":"backend","tag":"sha-${{ github.sha }}"}
